// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Promote Listing', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Promote Listing', async function() {
    await driver.get("https://chicagooglasi.com/")
    await driver.manage().window().setRect(1608, 1029)
    await driver.findElement(By.css(".main-nav:nth-child(1) .nav-item:nth-child(2) > .btn:nth-child(1)")).click()
    await driver.findElement(By.id("loginform-email")).click()
    await driver.findElement(By.id("loginform-email")).sendKeys("admin")
    await driver.findElement(By.id("loginform-password")).click()
    await driver.findElement(By.id("loginform-password")).sendKeys("singularity.is")
    await driver.findElement(By.name("login-button")).click()
    await driver.findElement(By.css(".main-nav:nth-child(1) > .header-menu-bar:nth-child(2) #user-dropdown")).click()
    await driver.findElement(By.linkText("Profile")).click()
    await driver.findElement(By.css(".grid__item:nth-child(10) .grid-view-item-image:nth-child(1)")).click()
    await driver.findElement(By.css(".d-none .btn-gold")).click()
    await driver.switchTo().frame(2)
    await driver.findElement(By.name("cardnumber")).click()
    await driver.findElement(By.name("cardnumber")).sendKeys("4242 4242 4242 4242")
    await driver.findElement(By.name("exp-date")).sendKeys("04 / 24")
    await driver.findElement(By.name("cvc")).sendKeys("242")
    await driver.findElement(By.name("postal")).sendKeys("42424")
    await driver.switchTo().defaultContent()
    await driver.findElement(By.name("login-button")).click()
    await driver.findElement(By.css(".main-nav:nth-child(1) > .header-menu-bar:nth-child(2) .nav-item:nth-child(1) > .nav-link:nth-child(1)")).click()
    await driver.wait(until.elementLocated(By.css(".grid__item:nth-child(1) .grid-view-item-image:nth-child(1)")), 30000)
  })
})
