// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Register business with services', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Register business with services', async function() {
    await driver.get("https://chicago-dev.singularity.is/")
    await driver.manage().window().setRect(1608, 1029)
    await driver.findElement(By.css(".main-nav:nth-child(1) .nav-item:nth-child(2) > .btn:nth-child(1)")).click()
    await driver.findElement(By.css(".link-blue:nth-child(3)")).click()
    await driver.findElement(By.id("shopsignupform-shop_name")).click()
    await driver.findElement(By.id("shopsignupform-shop_name")).sendKeys("Auto Test")
    await driver.findElement(By.css(".select2-search__field")).click()
    await driver.findElement(By.css(".select2-selection")).sendKeys("Advertising\\n")
    await driver.findElement(By.name("login-button")).click()
    await driver.findElement(By.id("signupform-name")).click()
    await driver.findElement(By.id("signupform-name")).sendKeys("Business Selenium")
    await driver.findElement(By.id("signupform-email")).click()
    await driver.findElement(By.id("signupform-email")).sendKeys("kisicol260@cnetmail.net")
    await driver.findElement(By.id("signupform-password")).click()
    await driver.findElement(By.css(".col-md-6:nth-child(5)")).click()
    {
      const element = await driver.findElement(By.css(".col-md-6:nth-child(5)"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    await driver.findElement(By.id("signupform-passwordrepeat")).click()
    await driver.findElement(By.id("signupform-passwordrepeat")).sendKeys("123456789")
    await driver.findElement(By.id("signupform-password")).click()
    await driver.findElement(By.id("signupform-password")).sendKeys("123456789")
    await driver.findElement(By.css(".custom-control-label")).click()
    await driver.switchTo().frame(0)
    await driver.findElement(By.css(".recaptcha-checkbox-border")).click()
    await driver.switchTo().defaultContent()
    await driver.switchTo().frame(1)
    await driver.findElement(By.id("recaptcha-verify-button")).click()
    await driver.switchTo().defaultContent()
    await driver.findElement(By.css(".mt-4")).click()
    await driver.wait(until.elementIsEnabled(await driver.findElement(By.name("login-button"))), 30000)
    raise Exception("`submit` is not a supported command in Selenium Webdriver. Please re-record the step in the IDE.")
    await driver.wait(until.elementLocated(By.css(".toast-success")), 30000)
  })
})
