// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Reset Password', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Reset Password', async function() {
    await driver.get("https://chicagooglasi.com/")
    await driver.manage().window().setRect(1608, 1029)
    await driver.findElement(By.css(".main-nav:nth-child(1) .nav-item:nth-child(2) > .btn:nth-child(1)")).click()
    await driver.findElement(By.css(".mt-2 > .link-blue")).click()
    await driver.findElement(By.id("passwordresetrequestform-email")).click()
    await driver.findElement(By.id("passwordresetrequestform-email")).sendKeys("emina.e.alatovic@gmail.com")
    await driver.findElement(By.name("login-button")).click()
    await driver.wait(until.elementLocated(By.css(".toast-message")), 30000)
  })
})
