// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Wrong Credentials Login', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Wrong Credentials Login', async function() {
    await driver.get("https://chicagooglasi.com/")
    await driver.manage().window().setRect(1608, 1029)
    await driver.findElement(By.css(".main-nav:nth-child(1) .nav-item:nth-child(2) > .btn:nth-child(1)")).click()
    await driver.findElement(By.id("loginform-email")).click()
    {
      const element = await driver.findElement(By.id("loginform-email"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    await driver.findElement(By.id("loginform-email")).sendKeys("unknown@email.com")
    await driver.findElement(By.id("loginform-password")).click()
    await driver.findElement(By.id("loginform-password")).sendKeys("0123456789")
    await driver.findElement(By.name("login-button")).click()
    await driver.wait(until.elementLocated(By.id("login-form-modal")), 30000)
  })
})
